version = "0.3.X"
[page]
seriesNavigation = true
# whether to enable last modified time
# 是否启用最后修改时间
enableLastMod = false
# whether to enable word count
# 是否启用字数统计
enableWordCount = true
# whether to enable reading time estimation
# 是否启用阅读时间估计
enableReadingTime = false
[page.math]
enable = true
blockLeftDelimiter = "\\["
blockRightDelimiter = "\\]"
inlineLeftDelimiter = "\\("
inlineRightDelimiter = "\\)"
copyTex = true
mhchem = true
[page.toc]
  # 是否使用目录
  enable = true
  # DoIt 新增 | 0.2.9 是否保持使用文章前面的静态目录
  keepStatic = false
[page.code]
  # 默认展开显示的代码行数
  maxShownLines = 1000

[page.comment]
  enable = false
[page.comment.disqus]
  enable = false
  shortname = ""
[page.comment.gitalk]
  clientId = ""
  clientSecret = ""
  enable = false
  owner = ""
  repo = ""


# 主页配置
[home]
# DoIt 新增 | 0.2.0 RSS 文章数目
  rss = 10
# 主页个人信息
[home.profile]
  enable = true
  # Gravatar 邮箱, 用于优先在主页显示的头像
  gravatarEmail = ""
  # 主页显示头像的 URL
  # 将你的头像文件放置于 static 或者 assets 目录下
  # 文件路径是相对于 static 或者 assets 目录的
  avatarURL = "/notion-avatar.png"
  # 头像的链接指向的 URL
  avatarLinkURL = ""
  # DoIt 更改 | 0.2.7 主页显示的网站标题 (支持 HTML 格式)
  title = ""
  # 主页显示的网站副标题
  subtitle = "好吃懒做，眼高手低"
  # 是否为副标题显示打字机动画
  typeit = true
  # 是否显示社交账号
  social = false
  # DoIt 新增 | 0.2.0 免责声明 (支持 HTML 格式)
  disclaimer = ""
# 主页文章列表
[home.posts]
  enable = true
  # 主页每页显示文章数量
  paginate = 5
  # DoIt 删除 | 0.2.0 被 params.page 中的 hiddenFromHomePage 替代
  # 当你没有在文章前置参数中设置 "hiddenFromHomePage" 时的默认行为
  defaultHiddenFromHomePage = false

[footer]
# 是否显示作者
author = false

[section]
paginate = 10